services:

  py99:
    image: hkim0331/py99:0.7.1
    environment:
      TZ: Asia/Tokyo
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - m2:/root/.m2
      - gitlibs:/root/.gitlibs
    ports:
      - "3099:3099"
    command:
      - sleep
      - infinity

  db:
    image: postgres:16
    environment:
      TZ: Asia/Tokyo
      POSTGRES_DB: py99
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --locale=C
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
      - data:/var/lib/postgresql/data

volumes:
  data:
    driver: local
  m2:
    external: true
  gitlibs:
    external: true
