version: "3"

services:
  py99:
    image: hkim0331/py99:0.4.4
    user : vscode
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - m2:/home/vscode/.m2
      - gitlibs:/home/vscode/.gitlibs
    command:
      - sleep
      - infinity

  db:
    image: postgres:14.9
    environment:
      POSTGRES_DB: py99
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --locale=C
      TZ: Asia/Toky
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
      - data:/var/lib/postgresql/data

volumes:
  data:
    driver: local
  m2:
    external: true
  gitlibs:
    external: true
