version: "3"

services:
  py99:
    image: hkim0331/py99:0.2
    user : vscode
    ports:
      - "3000:3000"
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - m2:/home/vscode/.m2
    command:
      - sleep
      - infinity

  db:
    image: postgres:14.9
    restart: always
    environment:
      POSTGRES_DB: py99
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --locale=C
      TZ: Asia/Toky
    # ports:
    #   - "55432:5432"
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
      - data:/var/lib/postgresql/data

volumes:
  data:
    driver: local
  m2:
    external: true
