version: "3"

services:
  py99:
    image: hkim0331/py99:0.4.7
    user : vscode
    working_dir: /usr/src/app
    environment:
      TZ: Asia/Tokyo
    volumes:
      - .:/usr/src/app
      # docker desktop v4.24.0, too slow.
      # v4.24.2 slow.
      # v4.27.0 slow 5m14s.
      - m2:/home/vscode/.m2
      - gitlibs:/home/vscode/.gitlibs
    command:
      - sleep
      - infinity

  db:
    image: postgres:14.10
    environment:
      TZ: Asia/Tokyo
      POSTGRES_DB: py99
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --locale=C
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
      - data:/var/lib/postgresql/data

volumes:
  data:
    driver: local
  m2:
    external: true
  gitlibs:
    external: true
